const jobsData = [
  {
    id: "job_001",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "#",
    description: "Join our core e-commerce team to build scalable backend services. You'll work closely with senior engineers to design, deploy, and maintain robust microservices using Java and AWS."
  },
  {
    id: "job_002",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Pune, Maharashtra",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "SQL", "Communication", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "3.5–4 LPA",
    applyUrl: "#",
    description: "We are looking for enthusiastic fresh graduates to join our enterprise solutions division. You'll undergo intensive training before being deployed on critical client projects."
  },
  {
    id: "job_003",
    title: "React Developer (1-3)",
    company: "Swiggy",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "Tailwind CSS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–15 LPA",
    applyUrl: "#",
    description: "Help us build the next generation of food delivery experiences. We need strong frontend engineers who care about web performance, animations, and building pixel-perfect UIs."
  },
  {
    id: "job_004",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Remote",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "Express", "PostgreSQL", "API Design"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "8–12 LPA",
    applyUrl: "#",
    description: "Join the payments revolution. You'll be maintaining and adding new features to our merchant dashboard APIs. Strong fundamental understanding of REST and databases is a must."
  },
  {
    id: "job_005",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bengaluru, Karnataka",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Tableau", "Excel"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "#",
    description: "Analyze vast amounts of e-commerce data to identify buying patterns and supply chain inefficiencies. Opportunity to convert to a full-time role based on performance."
  },
  {
    id: "job_006",
    title: "Python Developer (Fresher)",
    company: "Infosys",
    location: "Hyderabad, Telangana",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "REST APIs", "Git"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3.6–5 LPA",
    applyUrl: "#",
    description: "Looking for entry-level Python developers to support our cloud infrastructure team. You will be writing automation scripts and building microservices."
  },
  {
    id: "job_007",
    title: "Frontend Intern",
    company: "CRED",
    location: "Bengaluru, Karnataka",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React Native", "TypeScript", "UI/UX", "Animation"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹50k–₹70k/month Internship",
    applyUrl: "#",
    description: "Build beautiful, high-performance mobile interfaces for our members. You should have a keen eye for design and a passion for crafting smooth animations."
  },
  {
    id: "job_008",
    title: "QA Engineer (Automation)",
    company: "Zoho",
    location: "Chennai, Tamil Nadu",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Selenium", "Java", "TestNG", "CI/CD"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "6–9 LPA",
    applyUrl: "#",
    description: "Ensure the quality of our massive suite of SaaS products. You'll be writing automated test scripts, integrating with Jenkins, and maintaining our core test framework."
  },
  {
    id: "job_009",
    title: "Java Developer",
    company: "Wipro",
    location: "Pune, Maharashtra",
    mode: "Hybrid",
    experience: "3-5",
    skills: ["Java 11", "Spring Boot", "Microservices", "Kafka"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "12–18 LPA",
    applyUrl: "#",
    description: "Senior individual contributor role for banking client projects. Deep expertise in Spring Boot, distributed systems, and message queues is required."
  },
  {
    id: "job_010",
    title: "SDE-1",
    company: "PhonePe",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Distributed Systems", "MySQL", "Caching"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "15–22 LPA",
    applyUrl: "#",
    description: "Work on hyper-scale payment systems processing millions of transactions daily. We need sharp problem solvers who understand low-latency backend architectures."
  },
  {
    id: "job_011",
    title: "Full Stack Developer",
    company: "Juspay",
    location: "Remote",
    mode: "Remote",
    experience: "1-3",
    skills: ["PureScript", "Haskell", "React", "Functional Programming"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "14–20 LPA",
    applyUrl: "#",
    description: "Join our core payments routing team. We rely heavily on functional programming to ensure zero-defect payment systems. Functional programming knowledge is a strong plus."
  },
  {
    id: "job_012",
    title: "SDE Intern",
    company: "Paytm",
    location: "Noida, UP",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Node.js", "MongoDB", "Express", "API Design"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "#",
    description: "Intern with our ticketing operations team. You'll learn how to build APIs that can handle massive traffic spikes during newly released movie bookings."
  },
  {
    id: "job_013",
    title: "System Administrator",
    company: "IBM",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Linux", "Bash", "Networking", "Docker"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "5–8 LPA",
    applyUrl: "#",
    description: "Maintain core infrastructure for our enterprise hybrid cloud clients. Strong Linux troubleshooting skills and basic containerization knowledge required."
  },
  {
    id: "job_014",
    title: "Junior Cloud Engineer",
    company: "Accenture",
    location: "Mumbai, Maharashtra",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["AWS", "Azure", "Terraform", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "4.5–7 LPA",
    applyUrl: "#",
    description: "Assist in cloud migration projects for Fortune 500 companies. Get trained on the job for advanced AWS/Azure certifications."
  },
  {
    id: "job_015",
    title: "Software Engineer",
    company: "Freshworks",
    location: "Chennai, Tamil Nadu",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Ruby on Rails", "Ember.js", "MySQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "10–16 LPA",
    applyUrl: "#",
    description: "Enhance our customer support suite. You will be working directly on our core monolithic rails application and scaling it for millions of support agents globally."
  },
  {
    id: "job_016",
    title: "Frontend Developer",
    company: "Capgemini",
    location: "Pune, Maharashtra",
    mode: "Hybrid",
    experience: "3-5",
    skills: ["Angular", "TypeScript", "RxJS", "SCSS"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "9–14 LPA",
    applyUrl: "#",
    description: "Lead the frontend module for a major European banking client. Deep expertise in Angular and reactive programming paradigms is strictly required."
  },
  {
    id: "job_017",
    title: "Backend Developer (Go)",
    company: "Zepto",
    location: "Mumbai, Maharashtra",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Golang", "PostgreSQL", "gRPC", "Kubernetes"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "18–25 LPA",
    applyUrl: "#",
    description: "Build ultra low-latency delivery routing algorithms. We operate at extreme scale and need devs who understand concurrent programming in Go."
  },
  {
    id: "job_018",
    title: "QA Intern",
    company: "BrowserStack",
    location: "Remote",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Manual Testing", "JavaScript", "Selenium", "Appium"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "#",
    description: "Help test the platform that tests the internet. You will gain hands-on experience with native device testing, automation, and writing complex test cases."
  },
  {
    id: "job_019",
    title: "Technical Support Engineer",
    company: "Oracle",
    location: "Hyderabad, Telangana",
    mode: "Onsite",
    experience: "0-1",
    skills: ["SQL", "Oracle DB", "Linux", "Communication"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–6 LPA",
    applyUrl: "#",
    description: "Provide L2 support for enterprise database clients. Night shifts may apply. Excellent query optimization and troubleshooting skills are needed."
  },
  {
    id: "job_020",
    title: "Data Scientist",
    company: "Swiggy",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "3-5",
    skills: ["Python", "Machine Learning", "PyTorch", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "20–35 LPA",
    applyUrl: "#",
    description: "Optimize delivery ETAs and personalized restaurant recommendations. Experience with deep learning, spatial data, and massive datasets is highly preferred."
  },
  {
    id: "job_021",
    title: "App Developer (Flutter)",
    company: "Groww",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Flutter", "Dart", "State Management", "Firebase"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "12–18 LPA",
    applyUrl: "#",
    description: "Work on our core investing app used by millions of retail investors. We are migrating native flows to Flutter and need experts to guide the transition."
  },
  {
    id: "job_022",
    title: "React Developer (Fresher)",
    company: "Cognizant",
    location: "Chennai, Tamil Nadu",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "HTML5", "CSS3", "JavaScript"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "3.5–4.5 LPA",
    applyUrl: "#",
    description: "Entry-level position for an internal tools project. Good grasp of React hooks, context API, and modern Javascript ES6+ features expected."
  },
  {
    id: "job_023",
    title: "SDE 2 (Backend)",
    company: "Chargebee",
    location: "Chennai, Tamil Nadu",
    mode: "Remote",
    experience: "3-5",
    skills: ["Java", "Spring Boot", "AWS", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "25–38 LPA",
    applyUrl: "#",
    description: "Scale our recurring billing infrastructure. We process billions of dollars in subscriptions and require engineers who deeply understand concurrency, locking, and data consistency."
  },
  {
    id: "job_024",
    title: "iOS Developer",
    company: "Zomato",
    location: "Gurugram, Haryana",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Swift", "UIKit", "CoreData", "Combine"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "14–22 LPA",
    applyUrl: "#",
    description: "Build cutting-edge iOS features for our consumer app. Experience with modular architectures and performance profiling in Instruments is highly valued."
  },
  {
    id: "job_025",
    title: "Android Developer",
    company: "Zerodha",
    location: "Bengaluru, Karnataka",
    mode: "Remote",
    experience: "3-5",
    skills: ["Kotlin", "Coroutines", "Jetpack Compose", "MVVM"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "20–30 LPA",
    applyUrl: "#",
    description: "Help build Kite, the largest trading platform in India. Extreme focus on UI responsiveness, minimal network payloads, and robust socket connections."
  },
  {
    id: "job_026",
    title: "Security Analyst",
    company: "SAP",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Penetration Testing", "OWASP", "Network Security", "Python"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "8–12 LPA",
    applyUrl: "#",
    description: "Conduct routine vulnerability assessments and penetration testing on our enterprise cloud software. Work closely with devs to patch findings."
  },
  {
    id: "job_027",
    title: "UI/UX Designer",
    company: "Razorpay",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Figma", "Prototyping", "User Research", "Wireframing"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–16 LPA",
    applyUrl: "#",
    description: "Design seamless B2B payment experiences. You'll collaborate with PMs and engineers to turn complex financial jargon into simple, intuitive dashboards."
  },
  {
    id: "job_028",
    title: "DevOps Engineer",
    company: "Postman",
    location: "Bengaluru, Karnataka",
    mode: "Remote",
    experience: "3-5",
    skills: ["Kubernetes", "AWS", "Terraform", "CI/CD"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "22–35 LPA",
    applyUrl: "#",
    description: "Build internal developer platforms. We are migrating massive monolithic services to EKS and need experts in infrastructure as code and robust deployment pipelines."
  },
  {
    id: "job_029",
    title: "Junior Data Engineer",
    company: "Dell",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["SQL", "Python", "Spark", "ETL"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "6–9 LPA",
    applyUrl: "#",
    description: "Help build data pipelines for our global supply chain analytics team. You'll learn how to write optimized PySpark jobs and manage data lakes."
  },
  {
    id: "job_030",
    title: "SDE Intern (Frontend)",
    company: "Hasura",
    location: "Remote",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "TypeScript", "GraphQL", "Tailwind"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹40k–₹50k/month Internship",
    applyUrl: "#",
    description: "Work on the Hasura Cloud console. You will learn how to build complex, data-heavy React applications connecting directly to GraphQL endpoints."
  },
  {
    id: "job_031",
    title: "Business Analyst",
    company: "Accenture",
    location: "Gurugram, Haryana",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Agile", "Jira", "SQL", "Stakeholder Management"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "7–11 LPA",
    applyUrl: "#",
    description: "Bridge the gap between business requirements and technical implementation for our retail clients. Strong documentation and SQL skills needed."
  },
  {
    id: "job_032",
    title: "Rust Developer",
    company: "Kudos",
    location: "Pune, Maharashtra",
    mode: "Remote",
    experience: "1-3",
    skills: ["Rust", "Systems Programming", "WebAssembly", "C++"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "15–20 LPA",
    applyUrl: "#",
    description: "We are rewriting our core image processing engine in Rust. We need passionate systems programmers who care deeply about memory safety and performance."
  },
  {
    id: "job_033",
    title: "Customer Success Engineer",
    company: "Freshworks",
    location: "Chennai, Tamil Nadu",
    mode: "Onsite",
    experience: "0-1",
    skills: ["API Integration", "JavaScript", "HTML/CSS", "Communication"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "5–7 LPA",
    applyUrl: "#",
    description: "Help enterprise clients integrate our APIs into their workflows. You'll be writing custom scripts and debugging complex customer integrations."
  },
  {
    id: "job_034",
    title: "Site Reliability Engineer",
    company: "Flipkart",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "3-5",
    skills: ["Linux", "Go", "Prometheus", "Incident Management"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "20–30 LPA",
    applyUrl: "#",
    description: "Keep the Big Billion Days running smoothly. You will build observability tooling and manage high-severity incident responses for tier-1 services."
  },
  {
    id: "job_035",
    title: "C++ Developer",
    company: "Qualcomm",
    location: "Hyderabad, Telangana",
    mode: "Onsite",
    experience: "1-3",
    skills: ["C++", "RTOS", "Linux Kernel", "Debugging"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "14–22 LPA",
    applyUrl: "#",
    description: "Develop low-level drivers for our next generation of Snapdragon processors. Strong C/C++ knowledge and familiarity with OS internals required."
  },
  {
    id: "job_036",
    title: "Full Stack Engineer (MERN)",
    company: "Upstox",
    location: "Mumbai, Maharashtra",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["MongoDB", "Express", "React", "Node.js"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "12–18 LPA",
    applyUrl: "#",
    description: "Work on internal administration panels. You'll take full ownership of features from database schema design to frontend components."
  },
  {
    id: "job_037",
    title: "Data Analyst",
    company: "Amazon",
    location: "Bengaluru, Karnataka",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["SQL", "Excel", "Quicksight", "Python"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "8–14 LPA",
    applyUrl: "#",
    description: "Generate insights for the prime video acquisition team. You will be building automated dashboards and running complex ad-hoc queries."
  },
  {
    id: "job_038",
    title: "Software Engineer Trainee",
    company: "Cognizant",
    location: "Kolkata, West Bengal",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "OOP", "HTML/CSS"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3.5–4 LPA",
    applyUrl: "#",
    description: "Join our next batch of campus recruits. We provide 3 months of rigorous technical training before assigning you to enterprise projects."
  },
  {
    id: "job_039",
    title: "Blockchain Engineer",
    company: "Polygon",
    location: "Remote",
    mode: "Remote",
    experience: "3-5",
    skills: ["Solidity", "Rust", "Ethereum", "Cryptography"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "40–60 LPA",
    applyUrl: "#",
    description: "Work on the core zkEVM protocol. Only apply if you have deep understanding of cryptography and EVM internals."
  },
  {
    id: "job_040",
    title: "Node.js Developer",
    company: "Ola",
    location: "Bengaluru, Karnataka",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Node.js", "Redis", "Socket.io", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "14–20 LPA",
    applyUrl: "#",
    description: "Build robust real-time location tracking services for our cab fleet. Experience with WebSockets and high-throughput logging expected."
  },
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `job_0${41 + i}`,
    title: ["Junior Network Engineer", "SEO Analyst", "Content Writer Intern", "Database Admin", "Product Design Intern", "Mobile QA Tester", "PHP Developer", "Cloud Solutions Architect", "Salesforce Admin", "Ruby Developer"][i % 10],
    company: ["Tech Mahindra", "Mindtree", "LTI", "Mphasis", "Hexaware", "Zensar", "Lenskart", "Nykaa", "Urban Company", "Dream11"][i % 10],
    location: ["Pune, Maharashtra", "Chennai, Tamil Nadu", "Bengaluru, Karnataka", "Noida, UP", "Mumbai, Maharashtra"][i % 5],
    mode: ["Remote", "Hybrid", "Onsite"][i % 3],
    experience: ["Fresher", "0-1", "1-3", "3-5"][i % 4],
    skills: [["Networking", "Cisco"], ["SEO", "Google Analytics"], ["Copywriting", "Wordpress"], ["MySQL", "Backup"], ["Figma", "Sketch"], ["Appium", "Jira"], ["PHP", "Laravel"], ["AWS", "System Design"], ["Salesforce", "CRM"], ["Ruby", "Rails"]][i % 10],
    source: ["LinkedIn", "Naukri", "Indeed"][i % 3],
    postedDaysAgo: i % 10,
    salaryRange: ["3–5 LPA", "6–10 LPA", "12–18 LPA", "₹15k–₹25k/month Internship"][i % 4],
    applyUrl: "#",
    description: "An exciting opportunity to join a growing team. We are looking for passionate individuals who want to make a difference and scale fast-paced technological environments."
  }))
];
